#!/bin/bash

set -e
original_folder=`pwd`
cd $(dirname $0)
current_folder=`pwd`
source ./conf

if [[ -d /$INSTALL_FOLDER ]]; then
  echo "Building process needs /$INSTALL_FOLDER. Please rename ( or move to bak folder ) your original /$INSTALL_FOLDER and run this script again."
  exit 1
fi
mkdir /$INSTALL_FOLDER

# Build dependencies
aptitude -y install git binutils lintian dh-make gnupg

if [[ -d $FILES_FOLDER/keys/ ]]
then
  set +e
  gpg --import $FILES_FOLDER/keys/pub.gpg
  gpg --allow-secret-key-import --import $FILES_FOLDER/keys/prv.gpg
  set -e
fi

# CF CLI
./scripts/cli

# CF Cloud Controller
./scripts/cloud_controller

# CF JOBS
./scripts/jobs

# CF UAA
./scripts/uaa

# CF VCAP
./scripts/registrar

# CF login server
./scripts/login

# CF DEA
./scripts/dea

# CF Warden
./scripts/warden

# CF rootfs
./scripts/rootfs

# CF buildpack cache
./scripts/buildpack

# CF Go-Router
./scripts/gorouter

# CF hm9000
./scripts/hm9000

rm -rf /$INSTALL_FOLDER
cd $original_folder

#cd ${BOSH_INSTALL_TARGET}
#cp -a ${BOSH_COMPILE_TARGET}/vcap-common vcap-common
#cd vcap-common
#/var/vcap/packages/ruby/bin/bundle install --local --deployment --without=development test
#среда, 12 февраля 2014 г.
#[15:17:22] Alexander Borovsky - Altoros: https://github.com/cloudfoundry/cf-release/tree/master/src/cf-registrar-bundle-for-identity
