#!/bin/bash

if [ `whoami` != root ]; then
  echo "Please run this script as root."
  exit 1;
fi

# Global vars

export BUILD=1
export GBL_VER=1

export CONF_FOLDER=$current_folder
export LIB_FOLDER=$current_folder/lib
export TMP_FOLDER=$current_folder/tmp
export PKGS_FOLDER=$current_folder/pkgs
export FILES_FOLDER=$current_folder/files
export SCRIPTS_FOLDER=$current_folder/scripts
export INSTALL_FOLDER="var/lib/cloudfoundry"
if [ ! -d "$TMP_FOLDER" ]; then
  mkdir $TMP_FOLDER
fi
if [ ! -d "$PKGS_FOLDER" ]; then
  mkdir $PKGS_FOLDER
fi
if [[ $1 == "deb" ]]
then
  export DASH_S=""
else
  export DASH_S="-S"
fi

export MAINTAINER_EMAIL="Cloud Foundry <cf-charm@altoros.com>"
#export DISTRO=saucy # 13.10
export DISTRO=trusty # 14.04

# Cloudfoundry CLI
export CF_CLI_REPO=https://github.com/cloudfoundry/cli.git
export CF_CLI_PKG_NAME="cfcli"
export CF_CLI_PKG_VERSION="1ppa"$BUILD

# CF Cloud Controller
export CF_CCONTROLLER_REPO=https://github.com/cloudfoundry/cloud_controller_ng.git
export CF_CCONTROLLER_PKG_NAME="cfcloudcontroller"
export CF_CCONTROLLER_PKG_VERSION="1ppa"$BUILD

# CF UAA
export CF_UAA_REPO=https://github.com/cloudfoundry/uaa.git
export CF_UAA_PKG_NAME="cfuaa"
export CF_UAA_PKG_VERSION="1ppa"$BUILD
  
# CF DEA
export CF_DEA_REPO=https://github.com/cloudfoundry/dea_ng.git
export CF_DEA_PKG_NAME="cfdea"
export CF_DEA_PKG_VERSION="1ppa"$BUILD

# CF Warden
export CF_WARDEN_REPO=https://github.com/cloudfoundry/warden.git
export CF_WARDEN_PKG_NAME="cfwarden"
export CF_WARDEN_PKG_VERSION="1ppa"$BUILD

# CF Go-Router
export CF_GOROUTER_REPO=https://github.com/cloudfoundry/gorouter.git
export CF_GOROUTER_PKG_NAME="cfgorouter"
export CF_GOROUTER_PKG_VERSION="1ppa"$BUILD

# CF rootfs
export CF_ROOTFS_PKG_NAME="cfrootfs"
export CF_ROOTFS_PKG_VERSION="1ppa"$BUILD

# Jobs
export CF_JOBS_RELEASE_REPO=https://github.com/cloudfoundry/cf-release.git
export CF_JOBS_BUILDER_REPO=https://github.com/Altoros/cf-job2package-tool.git
export CF_JOBS_PKG_VERSION="1ppa"$BUILD

# Example:
#   CF_JOBS=cloud_controller_ng:cfcloudcontrollerjob:cfcloudcontroller;uaa:cfuaajob:cfuaa
# Format:
#   Each job must be described as: 
#     job folder name, job package name, dependency package name
#     job folder name         - folder in https://github.com/cloudfoundry/cf-release/tree/master/jobs
#     job package name        - package name which will be used during packing the job
#     dependency package name - package which will be set as dependency for the job, 
#                               and it will be used as install folder
# Synrax: 
#   ; job delimiter
#   : values delimiter
CF_JOBS="cloud_controller_ng:cfcloudcontrollerjob:cfcloudcontroller"
CF_JOBS=$CF_JOBS";dea_next:cfdeajob:cfdea"
CF_JOBS=$CF_JOBS";gorouter:cfgorouterjob:cfgorouter"
CF_JOBS=$CF_JOBS";hm9000:cfhm9000job:cfhm9000"
#CF_JOBS=$CF_JOBS";login::"
#CF_JOBS=$CF_JOBS";nats::"
CF_JOBS=$CF_JOBS";uaa:cfuaajob:cfuaa"
export CF_JOBS


