#!/bin/bash

set -e
echo "=== Installing CF WARDEN ==="
aptitude -y install ruby1.9.3 ruby-bundler libmysqlclient-dev libpq-dev libsqlite3-dev libxslt1-dev zip

export PRJ=$CF_WARDEN_PKG_NAME
export UBUNTU_VERSION=$CF_WARDEN_PKG_VERSION
export SRC=$CF_WARDEN_REPO
source $LIB_FOLDER/begin
git clone $SRC /$INSTALL_FOLDER/$PRJ
cd /$INSTALL_FOLDER/$PRJ
git submodule update --init --recursive
bundle --standalone install

echo "Getting version..."
VERSION=$GBL_VER
PKG=$PRJ-$VERSION

cd -
echo "Building package structure..."
deb_dir_structure . $PKG $PRJ
mkdir -p ./$PKG/$INSTALL_FOLDER/
echo "Getting dependencies..."
DEPENDS="ruby | ruby-interpreter, ruby1.9.3, ruby-bundler, libmysqlclient-dev, libpq-dev, libsqlite3-dev, libxslt1-dev, zip"

echo "Set file permissions..."
deb_permissions ./$PKG/
deb_permissions /$INSTALL_FOLDER/$PRJ

echo "Packing gems..."
cd /$INSTALL_FOLDER/$PRJ
tar czf bundle.tar.gz bundle .bundle
rm -rf bundle .bundle .git*
cd -

echo "Moving project into the package dir..."
mv /$INSTALL_FOLDER/$PRJ ./$PKG/$INSTALL_FOLDER/

# Copy binaries and make them executable
for f in `find ./$PKG/$INSTALL_FOLDER/$PRJ/bin/ -type f -printf "%f\n"` 
do
echo "Wrapping ./bin/$f..."
cat<<EOL > ./$PKG/usr/bin/$f
#!/bin/sh

BUNDLE_GEMFILE=/$INSTALL_FOLDER/$PRJ/Gemfile bundle exec /$INSTALL_FOLDER/$PRJ/bin/$f

EOL
chmod 0755 ./$PKG/usr/bin/$f
# mans
echo "Creating man file for $f..."
cp $FILES_FOLDER/$PRJ/man ./$PKG/usr/share/man/man1/$f.1
sed -i "s|u_bin_name|${f^^}|" ./$PKG/usr/share/man/man1/$f.1
sed -i "s|day|$(date +%d)|" ./$PKG/usr/share/man/man1/$f.1
sed -i "s|month|$(date +%B)|" ./$PKG/usr/share/man/man1/$f.1
sed -i "s|year|$(date +%Y)|" ./$PKG/usr/share/man/man1/$f.1
sed -i "s|bin_name|$f|" ./$PKG/usr/share/man/man1/$f.1
sed -i "s|install_folder|$INSTALL_FOLDER|" ./$PKG/usr/share/man/man1/$f.1
sed -i "s|prj_name|$PRJ|" ./$PKG/usr/share/man/man1/$f.1
gzip -9 ./$PKG/usr/share/man/man1/$f.1
chmod 0644 ./$PKG/usr/share/man/man1/$f.1.gz
done

echo "Making source packages..."
cd ./$PKG/
dh_make --createorig --packagename $PRJ"_"$VERSION --packageclass "s" --copyright "apache" --yes
rm -rf debian
mkdir debian

echo "Copy rules and compat..."
cp $FILES_FOLDER/$PRJ/compat ./debian/
cp $FILES_FOLDER/$PRJ/rules ./debian/

echo "Creating control file..."
cp $FILES_FOLDER/$PRJ/control ./debian
sed -i "s|package_name|$PRJ|g" ./debian/control
sed -i "s|app_version-ubuntu_version|$VERSION-$UBUNTU_VERSION|g" ./debian/control
sed -i "s|maintainer|$MAINTAINER_EMAIL|g" ./debian/control
sed -i "s/DEPENDENCIES/$DEPENDS/g" ./debian/control
chmod 0644 ./debian/control

echo "Creating changelog file..."
cp $FILES_FOLDER/$PRJ/changelog ./debian
sed -i "s|package_name|$PRJ|g" ./debian/changelog
sed -i "s|distro|$DISTRO|g" ./debian/changelog
sed -i "s|app_version-ubuntu_version|$VERSION-$UBUNTU_VERSION|g" ./debian/changelog
sed -i "s|maintainer|$MAINTAINER_EMAIL|g" ./debian/changelog
sed -i "s|date|$(date -R)|g" ./debian/changelog
chmod 0644 ./debian/changelog

echo "Creating copyright file..."
cp $FILES_FOLDER/$PRJ/copyright ./debian/
sed -i "s|src|$SRC|g" ./debian/copyright
sed -i "s|package_name|$PRJ|g" ./debian/copyright
sed -i "s|year|$(date +%Y)|g" ./debian/copyright
cp ./$INSTALL_FOLDER/$PRJ/LICENSE ./debian/copyright.tmp
$LIB_FOLDER/replace_std_licenses ./debian/copyright.tmp
sed -i 's|, 59 Temple Place - Suite 330,||g' ./debian/copyright.tmp
sed -i 's|Boston, MA 02111-1307, USA.||g' ./debian/copyright.tmp
sed -i 's|, 51 Franklin Street, Fifth Floor, Boston, MA||g' ./debian/copyright.tmp
sed -i 's|02110-1301 USA.||g' ./debian/copyright.tmp
$LIB_FOLDER/cf_cli_copyright ./debian/copyright.tmp ./debian/copyright
rm ./debian/copyright.tmp
rm ./$INSTALL_FOLDER/$PRJ/LICENSE
chmod 0644 ./debian/copyright

echo "Creating postinstall... "
cp $FILES_FOLDER/$PRJ/postinst ./debian/
sed -i "s|install_folder|$INSTALL_FOLDER|" ./debian/postinst
sed -i "s|prj_name|$PRJ|" ./debian/postinst
chmod 0755 ./debian/postinst

echo "Creating preremove... "
cp $FILES_FOLDER/$PRJ/prerm ./debian/
sed -i "s|install_folder|$INSTALL_FOLDER|" ./debian/prerm
sed -i "s|prj_name|$PRJ|" ./debian/prerm
chmod 0755 ./debian/prerm

echo "Create Install script..."
cp $FILES_FOLDER/$PRJ/install ./debian/$PRJ.install
chmod 0644 ./debian/$PRJ.install

echo "Building packages..."
dpkg-buildpackage $DASH_S -rfakeroot
if [[ $DASH_S == "" ]]
then
  lintian ../$PRJ"_"$VERSION-$UBUNTU_VERSION"_"amd64.deb
fi

echo "Moving packages to $PKGS_FOLDER..."
cd ..
rm -rf $PKG
mv ./* $PKGS_FOLDER/
echo "Done"

source $LIB_FOLDER/end

